const b = {
  '@umijs/preset-built-in': {
    id: '@umijs/preset-built-in',
    key: 'builtIn',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/index.js',
    defaultConfig: null,
    isPreset: true,
  },
  '@umijs/preset-react': {
    id: '@umijs/preset-react',
    key: 'react',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/preset-react/lib/index.js',
    defaultConfig: null,
    isPreset: true,
  },
  './node_modules/umi/node_modules/@@/registerMethods': {
    id: './node_modules/umi/node_modules/@@/registerMethods',
    key: 'registerMethods',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/registerMethods.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/routes': {
    id: './node_modules/umi/node_modules/@@/routes',
    key: 'routes',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/routes.js',
    defaultConfig: null,
    config: { onChange: 'regenerateTmpFiles' },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/generateFiles/core/history': {
    id: './node_modules/umi/node_modules/@@/generateFiles/core/history',
    key: 'history',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js',
    defaultConfig: null,
    config: { default: { type: 'browser' }, onChange: 'regenerateTmpFiles' },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/generateFiles/core/plugin': {
    id: './node_modules/umi/node_modules/@@/generateFiles/core/plugin',
    key: 'plugin',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/plugin.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/generateFiles/core/polyfill': {
    id: './node_modules/umi/node_modules/@@/generateFiles/core/polyfill',
    key: 'polyfill',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/polyfill.js',
    defaultConfig: null,
    config: {},
  },
  './node_modules/umi/node_modules/@@/generateFiles/core/routes': {
    id: './node_modules/umi/node_modules/@@/generateFiles/core/routes',
    key: 'routes',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/routes.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/generateFiles/core/umiExports': {
    id: './node_modules/umi/node_modules/@@/generateFiles/core/umiExports',
    key: 'umiExports',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/umiExports.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/generateFiles/core/configTypes': {
    id: './node_modules/umi/node_modules/@@/generateFiles/core/configTypes',
    key: 'configTypes',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/configTypes.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/generateFiles/umi': {
    id: './node_modules/umi/node_modules/@@/generateFiles/umi',
    key: 'umi',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/umi.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/features/404': {
    id: './node_modules/umi/node_modules/@@/features/404',
    key: '404',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/404.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/alias': {
    id: './node_modules/umi/node_modules/@@/features/alias',
    key: 'alias',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/alias.js',
    defaultConfig: null,
    config: {
      default: {
        'react-router':
          '/Users/a/github/zzzzzz/umiapp/node_modules/react-router',
        'react-router-dom':
          '/Users/a/github/zzzzzz/umiapp/node_modules/react-router-dom',
        history:
          '/Users/a/github/zzzzzz/umiapp/node_modules/history-with-query',
      },
    },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/analyze': {
    id: './node_modules/umi/node_modules/@@/features/analyze',
    key: 'analyze',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/analyze.js',
    defaultConfig: null,
    config: {
      default: {
        analyzerMode: 'server',
        analyzerPort: 8888,
        openAnalyzer: true,
        generateStatsFile: false,
        statsFilename: 'stats.json',
        logLevel: 'info',
        defaultSizes: 'parsed',
      },
    },
  },
  './node_modules/umi/node_modules/@@/features/autoprefixer': {
    id: './node_modules/umi/node_modules/@@/features/autoprefixer',
    key: 'autoprefixer',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/autoprefixer.js',
    defaultConfig: null,
    config: { default: { flexbox: 'no-2009' } },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/base': {
    id: './node_modules/umi/node_modules/@@/features/base',
    key: 'base',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/base.js',
    defaultConfig: null,
    config: { default: '/' },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/chainWebpack': {
    id: './node_modules/umi/node_modules/@@/features/chainWebpack',
    key: 'chainWebpack',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/chainWebpack.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/chunks': {
    id: './node_modules/umi/node_modules/@@/features/chunks',
    key: 'chunks',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/chunks.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/cssLoader': {
    id: './node_modules/umi/node_modules/@@/features/cssLoader',
    key: 'cssLoader',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/cssLoader.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/cssModulesTypescriptLoader': {
    id: './node_modules/umi/node_modules/@@/features/cssModulesTypescriptLoader',
    key: 'cssModulesTypescriptLoader',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/cssModulesTypescriptLoader.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/cssnano': {
    id: './node_modules/umi/node_modules/@@/features/cssnano',
    key: 'cssnano',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/cssnano.js',
    defaultConfig: null,
    config: {
      default: { mergeRules: false, minifyFontValues: { removeQuotes: false } },
    },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/copy': {
    id: './node_modules/umi/node_modules/@@/features/copy',
    key: 'copy',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/copy.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/define': {
    id: './node_modules/umi/node_modules/@@/features/define',
    key: 'define',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/define.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/devScripts': {
    id: './node_modules/umi/node_modules/@@/features/devScripts',
    key: 'devScripts',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/devScripts.js',
    defaultConfig: null,
    config: {},
  },
  './node_modules/umi/node_modules/@@/features/devServer': {
    id: './node_modules/umi/node_modules/@@/features/devServer',
    key: 'devServer',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/devServer.js',
    defaultConfig: null,
    config: { default: {} },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/devtool': {
    id: './node_modules/umi/node_modules/@@/features/devtool',
    key: 'devtool',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/devtool.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/dynamicImport': {
    id: './node_modules/umi/node_modules/@@/features/dynamicImport',
    key: 'dynamicImport',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/dynamicImport.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/dynamicImportSyntax': {
    id: './node_modules/umi/node_modules/@@/features/dynamicImportSyntax',
    key: 'dynamicImportSyntax',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/dynamicImportSyntax.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/exportStatic': {
    id: './node_modules/umi/node_modules/@@/features/exportStatic',
    key: 'exportStatic',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/exportStatic.js',
    defaultConfig: null,
    config: {},
  },
  './node_modules/umi/node_modules/@@/features/externals': {
    id: './node_modules/umi/node_modules/@@/features/externals',
    key: 'externals',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/externals.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/extraBabelIncludes': {
    id: './node_modules/umi/node_modules/@@/features/extraBabelIncludes',
    key: 'extraBabelIncludes',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/extraBabelIncludes.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/extraBabelPlugins': {
    id: './node_modules/umi/node_modules/@@/features/extraBabelPlugins',
    key: 'extraBabelPlugins',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/extraBabelPlugins.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/extraBabelPresets': {
    id: './node_modules/umi/node_modules/@@/features/extraBabelPresets',
    key: 'extraBabelPresets',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/extraBabelPresets.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/extraPostCSSPlugins': {
    id: './node_modules/umi/node_modules/@@/features/extraPostCSSPlugins',
    key: 'extraPostCSSPlugins',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/extraPostCSSPlugins.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/forkTSChecker': {
    id: './node_modules/umi/node_modules/@@/features/forkTSChecker',
    key: 'forkTSChecker',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/forkTSChecker.js',
    defaultConfig: null,
    config: {},
  },
  './node_modules/umi/node_modules/@@/features/fastRefresh': {
    id: './node_modules/umi/node_modules/@@/features/fastRefresh',
    key: 'fastRefresh',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/fastRefresh.js',
    defaultConfig: null,
    config: {},
    enableBy: 'config',
  },
  './node_modules/umi/node_modules/@@/features/globalCSS': {
    id: './node_modules/umi/node_modules/@@/features/globalCSS',
    key: 'globalCss',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/globalCSS.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/features/globalJS': {
    id: './node_modules/umi/node_modules/@@/features/globalJS',
    key: 'globalJs',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/globalJS.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/features/hash': {
    id: './node_modules/umi/node_modules/@@/features/hash',
    key: 'hash',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/hash.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/ignoreMomentLocale': {
    id: './node_modules/umi/node_modules/@@/features/ignoreMomentLocale',
    key: 'ignoreMomentLocale',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ignoreMomentLocale.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/inlineLimit': {
    id: './node_modules/umi/node_modules/@@/features/inlineLimit',
    key: 'inlineLimit',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/inlineLimit.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/lessLoader': {
    id: './node_modules/umi/node_modules/@@/features/lessLoader',
    key: 'lessLoader',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/lessLoader.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/manifest': {
    id: './node_modules/umi/node_modules/@@/features/manifest',
    key: 'manifest',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/manifest.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/mfsu/mfsu': {
    id: './node_modules/umi/node_modules/@@/features/mfsu/mfsu',
    key: 'mfsu',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js',
    defaultConfig: null,
    config: {},
  },
  './node_modules/umi/node_modules/@@/features/mountElementId': {
    id: './node_modules/umi/node_modules/@@/features/mountElementId',
    key: 'mountElementId',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mountElementId.js',
    defaultConfig: null,
    config: { default: 'root' },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/mpa': {
    id: './node_modules/umi/node_modules/@@/features/mpa',
    key: 'mpa',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mpa.js',
    defaultConfig: null,
    config: {},
    enableBy: 'config',
  },
  './node_modules/umi/node_modules/@@/features/nodeModulesTransform': {
    id: './node_modules/umi/node_modules/@@/features/nodeModulesTransform',
    key: 'nodeModulesTransform',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/nodeModulesTransform.js',
    defaultConfig: null,
    config: { default: { type: 'all', exclude: [] } },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/outputPath': {
    id: './node_modules/umi/node_modules/@@/features/outputPath',
    key: 'outputPath',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/outputPath.js',
    defaultConfig: null,
    config: { default: 'dist' },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/plugins': {
    id: './node_modules/umi/node_modules/@@/features/plugins',
    key: 'plugins',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/plugins.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/postcssLoader': {
    id: './node_modules/umi/node_modules/@@/features/postcssLoader',
    key: 'postcssLoader',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/postcssLoader.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/presets': {
    id: './node_modules/umi/node_modules/@@/features/presets',
    key: 'presets',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/presets.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/proxy': {
    id: './node_modules/umi/node_modules/@@/features/proxy',
    key: 'proxy',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/proxy.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/publicPath': {
    id: './node_modules/umi/node_modules/@@/features/publicPath',
    key: 'publicPath',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/publicPath.js',
    defaultConfig: null,
    config: { default: '/' },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/runtimePublicPath': {
    id: './node_modules/umi/node_modules/@@/features/runtimePublicPath',
    key: 'runtimePublicPath',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/runtimePublicPath.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/ssr/ssr': {
    id: './node_modules/umi/node_modules/@@/features/ssr/ssr',
    key: 'ssr',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js',
    defaultConfig: null,
    config: {},
  },
  './node_modules/umi/node_modules/@@/features/singular': {
    id: './node_modules/umi/node_modules/@@/features/singular',
    key: 'singular',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/singular.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/styleLoader': {
    id: './node_modules/umi/node_modules/@@/features/styleLoader',
    key: 'styleLoader',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/styleLoader.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/targets': {
    id: './node_modules/umi/node_modules/@@/features/targets',
    key: 'targets',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/targets.js',
    defaultConfig: null,
    config: {
      default: {
        node: true,
        chrome: 49,
        firefox: 64,
        safari: 10,
        edge: 13,
        ios: 10,
      },
    },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/terserOptions': {
    id: './node_modules/umi/node_modules/@@/features/terserOptions',
    key: 'terserOptions',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/terserOptions.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/theme': {
    id: './node_modules/umi/node_modules/@@/features/theme',
    key: 'theme',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/theme.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/umiInfo': {
    id: './node_modules/umi/node_modules/@@/features/umiInfo',
    key: 'umiInfo',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/umiInfo.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/features/runtimeHistory': {
    id: './node_modules/umi/node_modules/@@/features/runtimeHistory',
    key: 'runtimeHistory',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/runtimeHistory.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/webpack5': {
    id: './node_modules/umi/node_modules/@@/features/webpack5',
    key: 'webpack5',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/webpack5.js',
    defaultConfig: null,
    config: {},
  },
  './node_modules/umi/node_modules/@@/features/workerLoader': {
    id: './node_modules/umi/node_modules/@@/features/workerLoader',
    key: 'workerLoader',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/workerLoader.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/html/favicon': {
    id: './node_modules/umi/node_modules/@@/features/html/favicon',
    key: 'favicon',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/html/favicon.js',
    defaultConfig: null,
    config: { onChange: 'regenerateTmpFiles' },
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/html/headScripts': {
    id: './node_modules/umi/node_modules/@@/features/html/headScripts',
    key: 'headScripts',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/html/headScripts.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/html/links': {
    id: './node_modules/umi/node_modules/@@/features/html/links',
    key: 'links',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/html/links.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/html/metas': {
    id: './node_modules/umi/node_modules/@@/features/html/metas',
    key: 'metas',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/html/metas.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/html/scripts': {
    id: './node_modules/umi/node_modules/@@/features/html/scripts',
    key: 'scripts',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/html/scripts.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/html/styles': {
    id: './node_modules/umi/node_modules/@@/features/html/styles',
    key: 'styles',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/html/styles.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/features/html/title': {
    id: './node_modules/umi/node_modules/@@/features/html/title',
    key: 'title',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/html/title.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/commands/build/build': {
    id: './node_modules/umi/node_modules/@@/commands/build/build',
    key: 'build',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/build/build.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/build/applyHtmlWebpackPlugin': {
    id: './node_modules/umi/node_modules/@@/commands/build/applyHtmlWebpackPlugin',
    key: 'applyHtmlWebpackPlugin',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/build/applyHtmlWebpackPlugin.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/config/config': {
    id: './node_modules/umi/node_modules/@@/commands/config/config',
    key: 'config',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/config/config.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/dev/dev': {
    id: './node_modules/umi/node_modules/@@/commands/dev/dev',
    key: 'dev',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/dev.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/dev/devCompileDone/devCompileDone':
    {
      id: './node_modules/umi/node_modules/@@/commands/dev/devCompileDone/devCompileDone',
      key: 'devCompileDone',
      path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/devCompileDone/devCompileDone.js',
      defaultConfig: null,
    },
  './node_modules/umi/node_modules/@@/commands/dev/mock/mock': {
    id: './node_modules/umi/node_modules/@@/commands/dev/mock/mock',
    key: 'mock',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/dev/mock/mock.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  './node_modules/umi/node_modules/@@/commands/generate/generate': {
    id: './node_modules/umi/node_modules/@@/commands/generate/generate',
    key: 'generate',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/generate/generate.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/help/help': {
    id: './node_modules/umi/node_modules/@@/commands/help/help',
    key: 'help',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/help/help.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/plugin/plugin': {
    id: './node_modules/umi/node_modules/@@/commands/plugin/plugin',
    key: 'plugin',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/plugin/plugin.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/version/version': {
    id: './node_modules/umi/node_modules/@@/commands/version/version',
    key: 'version',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/version/version.js',
    defaultConfig: null,
  },
  './node_modules/umi/node_modules/@@/commands/webpack/webpack': {
    id: './node_modules/umi/node_modules/@@/commands/webpack/webpack',
    key: 'webpack',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/webpack/webpack.js',
    defaultConfig: null,
  },
  './node_modules/@umijs/preset-react/lib/react': {
    id: './node_modules/@umijs/preset-react/lib/react',
    key: 'react',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/preset-react/lib/react.js',
    defaultConfig: null,
  },
  '@umijs/plugin-access': {
    id: '@umijs/plugin-access',
    key: 'access',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-access/lib/index.js',
    defaultConfig: null,
  },
  '@umijs/plugin-analytics': {
    id: '@umijs/plugin-analytics',
    key: 'analytics',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-analytics/lib/index.js',
    defaultConfig: null,
  },
  '@umijs/plugin-antd': {
    id: '@umijs/plugin-antd',
    key: 'antd',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-antd/lib/index.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  '@umijs/plugin-crossorigin': {
    id: '@umijs/plugin-crossorigin',
    key: 'crossorigin',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-crossorigin/lib/index.js',
    defaultConfig: null,
  },
  '@umijs/plugin-dva': {
    id: '@umijs/plugin-dva',
    key: 'dva',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-dva/lib/index.js',
    defaultConfig: null,
    config: {},
    enableBy: 'register',
  },
  '@umijs/plugin-initial-state': {
    id: '@umijs/plugin-initial-state',
    key: 'initialState',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-initial-state/lib/index.js',
    defaultConfig: null,
  },
  '@umijs/plugin-locale': {
    id: '@umijs/plugin-locale',
    key: 'locale',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-locale/lib/index.js',
    defaultConfig: null,
    config: {
      default: {
        baseNavigator: true,
        useLocalStorage: true,
        baseSeparator: '-',
        antd: true,
      },
    },
    enableBy: 'config',
  },
  '@umijs/plugin-layout': {
    id: '@umijs/plugin-layout',
    key: 'layout',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-layout/lib/index.js',
    defaultConfig: null,
    config: { onChange: 'regenerateTmpFiles' },
    enableBy: 'config',
  },
  '@umijs/plugin-model': {
    id: '@umijs/plugin-model',
    key: 'model',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-model/lib/index.js',
    defaultConfig: null,
  },
  '@umijs/plugin-request': {
    id: '@umijs/plugin-request',
    key: 'request',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-request/lib/index.js',
    defaultConfig: null,
    config: { default: { dataField: 'data' } },
    enableBy: 'register',
  },
  '@umijs/plugin-test': {
    id: '@umijs/plugin-test',
    key: 'test',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-test/lib/index.js',
    defaultConfig: null,
  },
  '@umijs/plugin-helmet': {
    id: '@umijs/plugin-helmet',
    key: 'helmet',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/@umijs/plugin-helmet/lib/index.js',
    defaultConfig: null,
  },
  './node_modules/umi/lib/plugins/umiAlias': {
    id: './node_modules/umi/lib/plugins/umiAlias',
    key: 'umiAlias',
    path: '/Users/a/github/zzzzzz/umiapp/node_modules/umi/lib/plugins/umiAlias.js',
    defaultConfig: null,
  },
};
