const b = {
  nodeModulesTransform: { type: 'none', exclude: [] },
  routes: [{ path: '/', component: '@/pages/index' }],
  fastRefresh: {},
  history: { type: 'browser' },
  alias: {
    'react-router': '/Users/a/github/zzzzzz/umiapp/node_modules/react-router',
    'react-router-dom':
      '/Users/a/github/zzzzzz/umiapp/node_modules/react-router-dom',
    history: '/Users/a/github/zzzzzz/umiapp/node_modules/history-with-query',
  },
  analyze: {
    analyzerMode: 'server',
    analyzerPort: 8888,
    openAnalyzer: true,
    generateStatsFile: false,
    statsFilename: 'stats.json',
    logLevel: 'info',
    defaultSizes: 'parsed',
  },
  autoprefixer: { flexbox: 'no-2009' },
  base: '/',
  cssnano: { mergeRules: false, minifyFontValues: { removeQuotes: false } },
  devServer: {},
  mountElementId: 'root',
  outputPath: 'dist',
  publicPath: '/',
  targets: {
    node: true,
    chrome: 49,
    firefox: 64,
    safari: 10,
    edge: 13,
    ios: 10,
  },
  theme: { 'root-entry-name': 'default' },
  locale: {
    baseNavigator: true,
    useLocalStorage: true,
    baseSeparator: '-',
    antd: true,
  },
  request: { dataField: 'data' },
};
